version: '3.8'

services:
  dockflow-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://test:test@postgres-test:5432/dockflow_test
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
    depends_on:
      - postgres-test
    networks:
      - dockflow-test

  postgres-test:
    image: postgres:17
    environment:
      - POSTGRES_DB=dockflow_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - dockflow-test

volumes:
  postgres_test_data:

networks:
  dockflow-test:
    driver: bridge 